### ISSUE TITLE
Cannot Accept Consecutive Samples

### ISSUE THREAD

**Issue by Oxygen-Chu** [nanamake/r22sdf#2]
When a FFT calculation is done, there are previous samples in feedback buffer, and the next FFT calculation uses these samples instead of ZEROS.
So the second calculation will be wrong?

**Comment by nanamake** [comment]
Consecutive samples are acceptable, but difficult to explain in words. There is a document that illustrates R2SDF. You may find it by searching for "PIPELINE IMPLEMENTATIONS OF THE FAST FOURIER TRANSFORM (FFT)".

**Comment by Oxygen-Chu** [comment]
I tried consecutive FFT frames. It only successes after the assertion of 1st-stage SPDF's "bf1_end". If new frame samples are feed into FFT before this signal asserted, the result is wrong.
The following snapshot indicate the timing of "bf1_end" and new FFT frame. And you may see a big gap (red highlighted line) between two consecutive FFT frames.
![Capture](https://user-images.githubusercontent.com/22520522/108620171-40a4e780-7465-11eb-9873-f330eee986d5.PNG)

**Comment by nanamake** [comment]
The front half of the input frame is buffered and then butterfly-calculated with the back half.
The front half of the butterfly result is output immediately, while the back half is output after being buffered.
When frames are input continuously, the output of the back half of the first frame and the buffering of the front half of the next frame are performed concurrently.
The butterfly calculation for the next frame starts after the output of the first frame ends.
No gaps are needed between frames.

**Comment by Oxygen-Chu** [comment]
Truly! It really works as you say. Continuous frame execution is successful, and the error residual is small (32-bit)
Thank you :- )
![Capture](https://user-images.githubusercontent.com/22520522/108667797-e4999c00-7514-11eb-838f-f7270341a40b.PNG)

**Comment by nanamake** [comment]
Thank you for the graph. I'm glad it went well.
